# **TASK: 2**

## Load a CSV file into a Pandas DataFrame. Perform operations like filtering data based on conditions, handling missing values, and calculating summary statistics

In [ ]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [ ]:
# Load the DataSet
DataSet = pd.read_csv("Data Cleaning and Preprocessing.csv")

In [ ]:
print(type(DataSet)) # To determine type of the DataSet object.

<class 'pandas.core.frame.DataFrame'>

The above output "<class 'pandas.core.frame.DataFrame'>" indicates that DataSet is an instance of the DataFrame class from the pandas library.

In [ ]:
'''This syntax gives a concise summary of a DataFrame, which includes information about the DataFrame's index, data types,
   and non-null values for each column. This method is particularly helpful for understanding the structure and
   cleanliness of the dataset at a glance.
'''
DataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      324 non-null    object
 1   Y-Kappa          324 non-null    float64
 2   ChipRate         319 non-null    float64
 3   BF-CMratio       307 non-null    float64
 4   BlowFlow         308 non-null    float64
 5   ChipLevel4       323 non-null    float64
 6   T-upperExt-2     322 non-null    float64
 7   T-lowerExt-2     322 non-null    float64
 8   UCZAA            299 non-null    float64
 9   WhiteFlow-4      323 non-null    float64
 10  AAWhiteSt-4      173 non-null    float64
 11  AA-Wood-4        323 non-null    float64
 12  ChipMoisture-4   323 non-null    float64
 13  SteamFlow-4      323 non-null    float64
 14  Lower-HeatT-3    322 non-null    float64
 15  Upper-HeatT-3    322 non-null    float64
 16  ChipMass-4       323 non-null    float64
 17  WeakLiquorF      323 non-null    float64
 18  BlackFlow-2      322 non-null    float64
 19  WeakWashF        323 non-null    float64
 20  SteamHeatF-3     322 non-null    float64
 21  T-Top-Chips-4    323 non-null    float64
 22  SulphidityL-4    173 non-null    float64
dtypes: float64(22), object(1)
memory usage: 58.3+ KB

In [ ]:
DataSet.head(10) # Display the first 10 rows of a DataFrame

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
5,1-08:00,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.34
6,1-09:00,13.49,13.700,98.186,1243.688,116.275,346.208,326.982,1.434,696.766,...,72.989,322.982,296.080,182.018,784.281,929.527,201.272,58.118,248.741,NaN
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.22
8,31-07:00,22.50,14.233,97.249,1346.900,330.325,352.687,328.894,1.480,591.827,...,68.791,331.485,303.488,174.804,889.516,1317.912,226.319,52.546,250.414,NaN
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.21

In [ ]:
DataSet.tail(10) # Display the last 10 rows of a DataFrame

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
314,8-13:00,16.70,NaN,NaN,NaN,0.000,373.867,324.184,1.596,533.538,...,59.310,328.206,304.038,150.399,705.880,1145.549,481.277,50.671,250.683,29.252
315,8-14:00,16.05,13.114,NaN,NaN,0.000,NaN,NaN,1.648,500.376,...,55.180,329.185,303.149,141.763,865.254,NaN,491.514,47.943,251.696,NaN
316,8-15:00,17.75,11.283,NaN,NaN,41.607,362.545,331.240,1.658,467.265,...,50.663,NaN,NaN,128.396,836.060,1195.731,418.192,NaN,251.889,29.580
317,4-16:00,17.80,16.625,78.367,1276.082,202.744,360.127,329.266,1.488,698.486,...,75.296,321.658,297.088,180.438,1017.333,1052.785,433.089,54.675,251.747,30.320
318,4-17:00,18.20,16.283,83.508,1288.104,234.284,359.412,328.670,1.534,692.687,...,74.528,321.224,298.231,173.827,854.573,1174.267,62.077,50.653,252.474,NaN
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.860
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.700
321,9-20:00,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,...,66.446,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,NaN
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.130
323,9-22:00,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,...,58.247,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,NaN

In [ ]:
DataSet.shape # It returns a tuple representing the number of rows and columns in the DataFrame.
              # This is useful for quickly understanding the size of the dataset.

(324, 23)

In [ ]:
''' This method generates a summary of key statistical measures for numerical columns, and with the include parameter,
    it can also provide statistics for categorical columns. This summary includes metrics like count, mean, standard deviation,
    minimum, maximum, and the values at various percentiles. This metric are called 'Key Statistics'
'''
DataSet.describe() # descriptive statitics

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
count,324.000000,319.000000,307.000000,308.000000,323.000000,322.000000,322.000000,299.000000,323.000000,173.000000,...,323.000000,322.000000,322.000000,323.000000,323.000000,322.000000,323.000000,322.000000,323.000000,173.000000
mean,20.635370,14.347937,87.464456,1237.837614,258.164483,356.904295,324.020180,1.492010,591.732260,6.140410,...,66.668285,325.567820,300.525699,162.222322,873.828941,1175.917016,263.543068,49.696907,251.240087,30.411671
std,3.070036,1.499095,7.995012,100.593735,87.987452,9.209290,7.621402,0.105923,67.016351,0.081609,...,5.708587,4.609862,4.568484,14.160688,122.073521,149.334010,163.666942,4.551909,1.283432,0.701317
min,12.170000,9.983000,68.645000,0.000000,0.000000,339.168000,284.633000,1.182000,405.111000,5.890000,...,48.568000,318.051000,293.312000,113.922000,486.938000,838.948000,0.000000,35.510000,248.359000,29.010000
25%,18.382500,13.358000,81.823000,1193.215250,213.527000,350.241250,321.420000,1.431500,540.989500,6.089000,...,62.518000,321.385500,296.513250,153.032500,792.019500,1044.817500,134.649000,46.389750,250.312000,29.970000
50%,20.845000,14.308000,86.739000,1273.138500,271.792000,356.843000,325.669000,1.498000,592.895000,6.135000,...,67.429000,324.741000,299.126000,163.690000,865.254000,1150.221500,269.193000,50.277000,251.380000,30.370000
75%,23.032500,15.517000,92.372000,1289.196000,321.680000,362.242250,329.175000,1.560500,639.480500,6.199000,...,71.522000,329.845250,304.244750,172.555000,965.286500,1319.021250,405.563000,53.294250,252.323500,30.820000
max,27.600000,16.958000,121.717000,1351.240000,419.014000,399.135000,337.012000,1.747000,731.394000,6.340000,...,76.147000,333.854000,311.146000,189.268000,1226.277000,1395.767000,715.715000,63.332000,254.122000,32.840000

In [ ]:
# This method in pandas is used to remove duplicate rows from a DataFrame.
# By default, it considers all columns to identify duplicate rows, but it can also be configured to consider specific columns.
# The method returns a DataFrame with the duplicate rows removed.
DataSet = DataSet.drop_duplicates()
print(DataSet)

    Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4   \
0      31-00:00    23.10    16.520     121.717  1177.607      169.805
1      31-01:00    27.60    16.810      79.022  1328.360      341.327
2      31-02:00    23.19    16.709      79.562  1329.407      239.161
3      31-03:00    23.60    16.478      81.011  1334.877      213.527
4      31-04:00    22.90    15.618      93.244  1334.168      243.131
..          ...      ...       ...         ...       ...          ...
298    12-09:00    20.90    15.167      84.640  1283.706      339.440
299    12-10:00    24.98       NaN      85.034  1278.345      368.564
300    12-11:00    21.00       NaN      88.013  1307.722      278.842
301    12-12:00    21.40       NaN      85.490  1255.986      273.484
307    31-05:00    20.89    14.308      94.172  1327.832      251.120

     T-upperExt-2   T-lowerExt-2    UCZAA  WhiteFlow-4   ...  SteamFlow-4   \
0          358.282         329.545  1.443       599.253  ...        67.122
1          351.050         329.067  1.549       537.201  ...        60.012
2          350.022         329.260  1.600       549.611  ...        61.304
3          350.938         331.142  1.604       623.362  ...        68.496
4          351.640         332.709    NaN       638.672  ...        70.022
..             ...             ...    ...           ...  ...           ...
298        354.803         311.041  1.635       532.419  ...        65.561
299        357.723         321.387    NaN       520.365  ...        65.729
300        357.438         323.757    NaN       553.070  ...        65.795
301        361.365         322.689    NaN       590.199  ...        71.456
307        351.263         332.485  1.522       631.514  ...        71.286

     Lower-HeatT-3  Upper-HeatT-3   ChipMass-4   WeakLiquorF   BlackFlow-2   \
0          329.432         303.099      175.964      1127.197      1319.039
1          330.823         304.879      163.202       665.975      1297.317
2          329.140         303.383      164.013       677.534      1327.072
3          328.875         302.254      181.487       767.853      1324.461
4          328.352         300.954      183.929       888.448      1343.424
..             ...             ...          ...           ...           ...
298        332.924         307.626      145.299       832.906      1344.708
299        332.523         307.169      151.544       905.639      1344.469
300        331.263         306.400      157.954       908.691      1344.588
301        333.032         308.732      174.069       986.206      1348.747
307        328.699         300.706      180.229       903.605      1323.082

     WeakWashF   SteamHeatF-3   T-Top-Chips-4   SulphidityL-4
0       257.325         54.612         252.077             NaN
1       241.182         46.603         251.406           29.11
2       237.272         51.795         251.335             NaN
3       239.478         54.846         250.312           29.02
4       215.372         54.186         249.916           29.01
..          ...            ...             ...             ...
298     388.911         49.524         251.833           30.29
299     418.979         48.135         251.614           30.47
300     462.712         54.373         251.197             NaN
301     457.313         53.194         251.324           30.46
307     232.729         54.503         250.084             NaN

[301 rows x 23 columns]

In [ ]:
# This method in pandas is used to detect missing values in a DataFrame.
# It will return the elements in boolean values i.e. True and False where True means that element is (NaN) or none and False means that element is not null.
# This method is useful for identifying and handling missing data in your dataset.
DataSet.isnull()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
299,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
300,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
301,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
307,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
# From the above syntax it is hard to find how many elements in particular column are null in the DataSet, so there is an another syntax
# below where we can count the no. of missing values in particular column

In [ ]:
DataSet.isnull().sum() # To count the number of missing values in each column

Observation          0
Y-Kappa              0
ChipRate             4
BF-CMratio          14
BlowFlow            13
ChipLevel4           1
T-upperExt-2         1
T-lowerExt-2         1
UCZAA               24
WhiteFlow-4          1
AAWhiteSt-4        141
AA-Wood-4            1
ChipMoisture-4       1
SteamFlow-4          1
Lower-HeatT-3        1
Upper-HeatT-3        1
ChipMass-4           1
WeakLiquorF          1
BlackFlow-2          1
WeakWashF            1
SteamHeatF-3         1
T-Top-Chips-4        1
SulphidityL-4      141
dtype: int64

In [ ]:
DataSet.notnull() # Returns a DataFrame with boolean values, where True indicates non-missing values and False Indicates null values

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
299,True,True,False,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
300,True,True,False,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,False
301,True,True,False,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
307,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False

In [ ]:
# This method is used to count the number of non-null (non-missing) entries in each column of a DataFrame.
# This is useful for quickly getting an overview of the completeness of data.
DataSet.notnull().sum()

Observation        301
Y-Kappa            301
ChipRate           297
BF-CMratio         287
BlowFlow           288
ChipLevel4         300
T-upperExt-2       300
T-lowerExt-2       300
UCZAA              277
WhiteFlow-4        300
AAWhiteSt-4        160
AA-Wood-4          300
ChipMoisture-4     300
SteamFlow-4        300
Lower-HeatT-3      300
Upper-HeatT-3      300
ChipMass-4         300
WeakLiquorF        300
BlackFlow-2        300
WeakWashF          300
SteamHeatF-3       300
T-Top-Chips-4      300
SulphidityL-4      160
dtype: int64

In [ ]:
# "DataSet.isnull()": This method returns a DataFrame of the same shape as DataSet, with boolean values indicating,
# where the missing values (NaNs) are (True for missing, False for non-missing).


# "sum().sum()": The first sum() calculates the sum of True values (which are treated as 1) for each column,
# giving a Series where each element represents the number of missing values in a column.
# The second sum() then calculates the sum of this Series, giving the total number of missing values in the entire DataFrame.

DataSet.isnull().sum().sum() # This method is used to calculate the total number of missing values in an entire DataFrame.

352

In [ ]:
DataSet1 = DataSet.fillna(value=0) # fillna() is used to fill missing (NaN) values in the DataFrame or Series.
                                   # (value=0) is a parameter of the fillna() method. It specifies the value
                                   # that will be used to fill in the missing values. In this case,we are filling missing values with 0.

print(DataSet1)

    Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4   \
0      31-00:00    23.10    16.520     121.717  1177.607      169.805
1      31-01:00    27.60    16.810      79.022  1328.360      341.327
2      31-02:00    23.19    16.709      79.562  1329.407      239.161
3      31-03:00    23.60    16.478      81.011  1334.877      213.527
4      31-04:00    22.90    15.618      93.244  1334.168      243.131
..          ...      ...       ...         ...       ...          ...
298    12-09:00    20.90    15.167      84.640  1283.706      339.440
299    12-10:00    24.98     0.000      85.034  1278.345      368.564
300    12-11:00    21.00     0.000      88.013  1307.722      278.842
301    12-12:00    21.40     0.000      85.490  1255.986      273.484
307    31-05:00    20.89    14.308      94.172  1327.832      251.120

     T-upperExt-2   T-lowerExt-2    UCZAA  WhiteFlow-4   ...  SteamFlow-4   \
0          358.282         329.545  1.443       599.253  ...        67.122
1          351.050         329.067  1.549       537.201  ...        60.012
2          350.022         329.260  1.600       549.611  ...        61.304
3          350.938         331.142  1.604       623.362  ...        68.496
4          351.640         332.709  0.000       638.672  ...        70.022
..             ...             ...    ...           ...  ...           ...
298        354.803         311.041  1.635       532.419  ...        65.561
299        357.723         321.387  0.000       520.365  ...        65.729
300        357.438         323.757  0.000       553.070  ...        65.795
301        361.365         322.689  0.000       590.199  ...        71.456
307        351.263         332.485  1.522       631.514  ...        71.286

     Lower-HeatT-3  Upper-HeatT-3   ChipMass-4   WeakLiquorF   BlackFlow-2   \
0          329.432         303.099      175.964      1127.197      1319.039
1          330.823         304.879      163.202       665.975      1297.317
2          329.140         303.383      164.013       677.534      1327.072
3          328.875         302.254      181.487       767.853      1324.461
4          328.352         300.954      183.929       888.448      1343.424
..             ...             ...          ...           ...           ...
298        332.924         307.626      145.299       832.906      1344.708
299        332.523         307.169      151.544       905.639      1344.469
300        331.263         306.400      157.954       908.691      1344.588
301        333.032         308.732      174.069       986.206      1348.747
307        328.699         300.706      180.229       903.605      1323.082

     WeakWashF   SteamHeatF-3   T-Top-Chips-4   SulphidityL-4
0       257.325         54.612         252.077            0.00
1       241.182         46.603         251.406           29.11
2       237.272         51.795         251.335            0.00
3       239.478         54.846         250.312           29.02
4       215.372         54.186         249.916           29.01
..          ...            ...             ...             ...
298     388.911         49.524         251.833           30.29
299     418.979         48.135         251.614           30.47
300     462.712         54.373         251.197            0.00
301     457.313         53.194         251.324           30.46
307     232.729         54.503         250.084            0.00

[301 rows x 23 columns]

In [ ]:
DataSet1.tail(20)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
283,11-18:00,20.37,10.967,99.982,998.153,302.251,344.295,305.080,1.604,471.537,...,57.260,330.293,304.958,136.358,1067.280,1346.973,237.346,40.713,252.545,30.40
284,11-19:00,20.20,9.983,102.237,1027.485,369.632,342.576,298.560,1.639,454.091,...,54.259,328.976,304.282,130.177,1000.752,1361.314,3.880,41.850,252.565,0.00
285,11-20:00,18.83,10.967,94.472,1036.043,314.321,340.338,287.705,1.515,473.012,...,56.395,330.224,305.311,136.167,922.424,1356.425,111.716,41.256,252.474,30.35
286,11-21:00,19.53,11.245,92.564,1040.922,384.977,342.790,284.633,1.368,444.580,...,53.822,329.335,305.521,124.682,845.214,1301.950,209.575,39.368,252.479,0.00
287,11-22:00,21.20,11.292,92.194,1041.020,388.538,341.538,297.247,1.457,405.111,...,51.192,328.289,305.824,113.922,838.094,1292.599,353.625,38.642,253.161,30.57
288,11-23:00,22.10,10.933,97.752,1038.618,333.743,343.695,305.528,0.000,437.205,...,56.182,329.052,307.915,122.927,910.166,1294.447,386.579,39.162,253.796,30.75
289,12-00:00,22.50,10.625,89.193,1010.855,322.470,342.637,305.806,1.571,447.743,...,58.147,330.078,307.162,130.474,848.433,1290.827,390.214,42.822,253.180,0.00
290,12-01:00,19.90,11.333,87.405,1033.565,369.383,343.515,302.364,1.592,452.718,...,55.963,330.842,308.789,128.701,783.417,1293.108,390.049,41.596,252.428,30.73
291,12-02:00,21.00,11.825,90.949,1078.498,393.486,345.109,308.647,1.499,443.581,...,55.516,330.234,308.253,126.221,820.750,1294.998,390.281,39.561,252.836,0.00
292,12-03:00,22.00,11.858,93.199,1171.206,366.787,345.261,310.115,1.513,428.202,...,52.494,330.589,309.152,122.011,816.020,1294.891,391.607,42.080,253.206,30.24
293,12-04:00,19.50,12.567,96.937,1204.438,300.098,345.516,311.489,1.578,454.678,...,58.135,330.093,307.904,121.490,918.355,1296.989,388.881,44.507,253.308,0.00
294,12-05:00,19.00,12.425,92.905,1272.030,316.226,345.811,307.806,1.633,469.045,...,60.307,329.997,308.072,137.719,865.661,1292.216,391.645,44.330,253.323,30.31
295,12-06:00,19.20,13.692,95.157,1298.896,356.708,347.293,307.003,1.501,471.791,...,58.089,329.527,307.095,132.975,914.133,1317.664,390.061,47.614,252.850,0.00
296,12-07:00,20.50,13.358,97.662,1304.597,377.678,347.672,313.147,1.546,496.460,...,60.119,332.615,308.575,141.076,997.904,1334.703,389.497,46.206,252.423,30.43
297,12-08:00,20.40,14.233,89.790,1278.006,379.458,354.290,315.558,1.515,491.374,...,60.424,331.980,308.078,140.301,975.016,1344.835,388.676,47.803,252.311,0.00
298,12-09:00,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29
299,12-10:00,24.98,0.000,85.034,1278.345,368.564,357.723,321.387,0.000,520.365,...,65.729,332.523,307.169,151.544,905.639,1344.469,418.979,48.135,251.614,30.47
300,12-11:00,21.00,0.000,88.013,1307.722,278.842,357.438,323.757,0.000,553.070,...,65.795,331.263,306.400,157.954,908.691,1344.588,462.712,54.373,251.197,0.00
301,12-12:00,21.40,0.000,85.490,1255.986,273.484,361.365,322.689,0.000,590.199,...,71.456,333.032,308.732,174.069,986.206,1348.747,457.313,53.194,251.324,30.46
307,31-05:00,20.89,14.308,94.172,1327.832,251.120,351.263,332.485,1.522,631.514,...,71.286,328.699,300.706,180.229,903.605,1323.082,232.729,54.503,250.084,0.00

In [ ]:
DataSet1.isnull().sum().sum()

0

In [ ]:
DataSet

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,12-09:00,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29
299,12-10:00,24.98,NaN,85.034,1278.345,368.564,357.723,321.387,NaN,520.365,...,65.729,332.523,307.169,151.544,905.639,1344.469,418.979,48.135,251.614,30.47
300,12-11:00,21.00,NaN,88.013,1307.722,278.842,357.438,323.757,NaN,553.070,...,65.795,331.263,306.400,157.954,908.691,1344.588,462.712,54.373,251.197,NaN
301,12-12:00,21.40,NaN,85.490,1255.986,273.484,361.365,322.689,NaN,590.199,...,71.456,333.032,308.732,174.069,986.206,1348.747,457.313,53.194,251.324,30.46
307,31-05:00,20.89,14.308,94.172,1327.832,251.120,351.263,332.485,1.522,631.514,...,71.286,328.699,300.706,180.229,903.605,1323.082,232.729,54.503,250.084,NaN

In [ ]:
DataSet2 = DataSet.fillna(method = 'pad') # DataFrame will be filled with the preceding non-missing value in the respective column.
print(DataSet2)

    Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4   \
0      31-00:00    23.10    16.520     121.717  1177.607      169.805
1      31-01:00    27.60    16.810      79.022  1328.360      341.327
2      31-02:00    23.19    16.709      79.562  1329.407      239.161
3      31-03:00    23.60    16.478      81.011  1334.877      213.527
4      31-04:00    22.90    15.618      93.244  1334.168      243.131
..          ...      ...       ...         ...       ...          ...
298    12-09:00    20.90    15.167      84.640  1283.706      339.440
299    12-10:00    24.98    15.167      85.034  1278.345      368.564
300    12-11:00    21.00    15.167      88.013  1307.722      278.842
301    12-12:00    21.40    15.167      85.490  1255.986      273.484
307    31-05:00    20.89    14.308      94.172  1327.832      251.120

     T-upperExt-2   T-lowerExt-2    UCZAA  WhiteFlow-4   ...  SteamFlow-4   \
0          358.282         329.545  1.443       599.253  ...        67.122
1          351.050         329.067  1.549       537.201  ...        60.012
2          350.022         329.260  1.600       549.611  ...        61.304
3          350.938         331.142  1.604       623.362  ...        68.496
4          351.640         332.709  1.604       638.672  ...        70.022
..             ...             ...    ...           ...  ...           ...
298        354.803         311.041  1.635       532.419  ...        65.561
299        357.723         321.387  1.635       520.365  ...        65.729
300        357.438         323.757  1.635       553.070  ...        65.795
301        361.365         322.689  1.635       590.199  ...        71.456
307        351.263         332.485  1.522       631.514  ...        71.286

     Lower-HeatT-3  Upper-HeatT-3   ChipMass-4   WeakLiquorF   BlackFlow-2   \
0          329.432         303.099      175.964      1127.197      1319.039
1          330.823         304.879      163.202       665.975      1297.317
2          329.140         303.383      164.013       677.534      1327.072
3          328.875         302.254      181.487       767.853      1324.461
4          328.352         300.954      183.929       888.448      1343.424
..             ...             ...          ...           ...           ...
298        332.924         307.626      145.299       832.906      1344.708
299        332.523         307.169      151.544       905.639      1344.469
300        331.263         306.400      157.954       908.691      1344.588
301        333.032         308.732      174.069       986.206      1348.747
307        328.699         300.706      180.229       903.605      1323.082

     WeakWashF   SteamHeatF-3   T-Top-Chips-4   SulphidityL-4
0       257.325         54.612         252.077             NaN
1       241.182         46.603         251.406           29.11
2       237.272         51.795         251.335           29.11
3       239.478         54.846         250.312           29.02
4       215.372         54.186         249.916           29.01
..          ...            ...             ...             ...
298     388.911         49.524         251.833           30.29
299     418.979         48.135         251.614           30.47
300     462.712         54.373         251.197           30.47
301     457.313         53.194         251.324           30.46
307     232.729         54.503         250.084           30.46

[301 rows x 23 columns]

In [ ]:
DataSet3 = DataSet.fillna(method = 'bfill')  # Any missing values in the DataFrame or Series named DataSet will be filled with the next non-missing value in the respective column.
print(DataSet3)

    Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4   \
0      31-00:00    23.10    16.520     121.717  1177.607      169.805
1      31-01:00    27.60    16.810      79.022  1328.360      341.327
2      31-02:00    23.19    16.709      79.562  1329.407      239.161
3      31-03:00    23.60    16.478      81.011  1334.877      213.527
4      31-04:00    22.90    15.618      93.244  1334.168      243.131
..          ...      ...       ...         ...       ...          ...
298    12-09:00    20.90    15.167      84.640  1283.706      339.440
299    12-10:00    24.98    14.308      85.034  1278.345      368.564
300    12-11:00    21.00    14.308      88.013  1307.722      278.842
301    12-12:00    21.40    14.308      85.490  1255.986      273.484
307    31-05:00    20.89    14.308      94.172  1327.832      251.120

     T-upperExt-2   T-lowerExt-2    UCZAA  WhiteFlow-4   ...  SteamFlow-4   \
0          358.282         329.545  1.443       599.253  ...        67.122
1          351.050         329.067  1.549       537.201  ...        60.012
2          350.022         329.260  1.600       549.611  ...        61.304
3          350.938         331.142  1.604       623.362  ...        68.496
4          351.640         332.709  1.436       638.672  ...        70.022
..             ...             ...    ...           ...  ...           ...
298        354.803         311.041  1.635       532.419  ...        65.561
299        357.723         321.387  1.522       520.365  ...        65.729
300        357.438         323.757  1.522       553.070  ...        65.795
301        361.365         322.689  1.522       590.199  ...        71.456
307        351.263         332.485  1.522       631.514  ...        71.286

     Lower-HeatT-3  Upper-HeatT-3   ChipMass-4   WeakLiquorF   BlackFlow-2   \
0          329.432         303.099      175.964      1127.197      1319.039
1          330.823         304.879      163.202       665.975      1297.317
2          329.140         303.383      164.013       677.534      1327.072
3          328.875         302.254      181.487       767.853      1324.461
4          328.352         300.954      183.929       888.448      1343.424
..             ...             ...          ...           ...           ...
298        332.924         307.626      145.299       832.906      1344.708
299        332.523         307.169      151.544       905.639      1344.469
300        331.263         306.400      157.954       908.691      1344.588
301        333.032         308.732      174.069       986.206      1348.747
307        328.699         300.706      180.229       903.605      1323.082

     WeakWashF   SteamHeatF-3   T-Top-Chips-4   SulphidityL-4
0       257.325         54.612         252.077           29.11
1       241.182         46.603         251.406           29.11
2       237.272         51.795         251.335           29.02
3       239.478         54.846         250.312           29.02
4       215.372         54.186         249.916           29.01
..          ...            ...             ...             ...
298     388.911         49.524         251.833           30.29
299     418.979         48.135         251.614           30.47
300     462.712         54.373         251.197           30.46
301     457.313         53.194         251.324           30.46
307     232.729         54.503         250.084             NaN

[301 rows x 23 columns]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [ ]:
#Detect the outliers using IQR
DataSet1.columns

Index(['Observation', 'Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow',
       'ChipLevel4 ', 'T-upperExt-2 ', 'T-lowerExt-2  ', 'UCZAA',
       'WhiteFlow-4 ', 'AAWhiteSt-4 ', 'AA-Wood-4  ', 'ChipMoisture-4 ',
       'SteamFlow-4 ', 'Lower-HeatT-3', 'Upper-HeatT-3 ', 'ChipMass-4 ',
       'WeakLiquorF ', 'BlackFlow-2 ', 'WeakWashF ', 'SteamHeatF-3 ',
       'T-Top-Chips-4 ', 'SulphidityL-4 '],
      dtype='object')

In [ ]:
# This syntax in pandas is used to drop a column named 'Observation' from the DataFrame DataSet1.
# This operation removes the specified column from the DataFrame.
# The inplace=True parameter ensures that the operation is performed directly on the original DataFrame DataSet1 without the need for reassignment.

DataSet1.drop(['Observation'], axis = 1, inplace = True)

In [ ]:
DataSet1.columns

Index(['Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow', 'ChipLevel4 ',
       'T-upperExt-2 ', 'T-lowerExt-2  ', 'UCZAA', 'WhiteFlow-4 ',
       'AAWhiteSt-4 ', 'AA-Wood-4  ', 'ChipMoisture-4 ', 'SteamFlow-4 ',
       'Lower-HeatT-3', 'Upper-HeatT-3 ', 'ChipMass-4 ', 'WeakLiquorF ',
       'BlackFlow-2 ', 'WeakWashF ', 'SteamHeatF-3 ', 'T-Top-Chips-4 ',
       'SulphidityL-4 '],
      dtype='object')

In [ ]:
#'DataSet1.quantile(0.25)': This method call calculates the first quartile (Q1) for each column in the DataFrame DataSet1.
# The parameter 0.25 specifies that the first quartile should be calculated, which corresponds to the 25th percentile.

Q_1 = DataSet1.quantile(0.25)

# DataSet1.quantile(0.75): Similarly, this method call calculates the third quartile (Q3) for each column in the DataFrame DataSet1.
# The parameter 0.75 specifies that the third quartile should be calculated, which corresponds to the 75th percentile.
Q_3 = DataSet1.quantile(0.75)

# The IQR is a measure of statistical dispersion and is often used in descriptive statistics to identify the spread of the middle 50% of the dataset.
# Calculate IQR
IQR = Q_3 - Q_1
print("IQR is:\n",IQR)

IQR is:
 Y-Kappa              4.550
ChipRate             2.233
BF-CMratio          10.912
BlowFlow            96.766
ChipLevel4         105.868
T-upperExt-2        11.994
T-lowerExt-2         7.609
UCZAA                0.152
WhiteFlow-4        100.098
AAWhiteSt-4          6.143
AA-Wood-4            1.486
ChipMoisture-4       2.186
SteamFlow-4          8.840
Lower-HeatT-3        8.585
Upper-HeatT-3        7.852
ChipMass-4          19.347
WeakLiquorF        180.613
BlackFlow-2        280.829
WeakWashF          267.219
SteamHeatF-3         6.903
T-Top-Chips-4        2.044
SulphidityL-4       30.420
dtype: float64

In [ ]:
# This code performs outlier detection and removal in the DataFrame 'DataSet1' based on the Interquartile Range (IQR) method
DataSet1 = DataSet1 [ ~ ((DataSet1 < (Q_1 - 1.5 * IQR)) | (DataSet1 > (Q_3 + 1.5* IQR))).any (axis = 1)]
print(DataSet1)

     Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4   T-upperExt-2   \
1      27.60    16.810      79.022  1328.360      341.327        351.050
2      23.19    16.709      79.562  1329.407      239.161        350.022
3      23.60    16.478      81.011  1334.877      213.527        350.938
5      14.23    15.350      85.518  1171.604      198.538        344.014
6      13.49    13.700      98.186  1243.688      116.275        346.208
..       ...       ...         ...       ...          ...            ...
276    22.70    15.517      83.008  1288.010      306.886        350.155
296    20.50    13.358      97.662  1304.597      377.678        347.672
297    20.40    14.233      89.790  1278.006      379.458        354.290
298    20.90    15.167      84.640  1283.706      339.440        354.803
307    20.89    14.308      94.172  1327.832      251.120        351.263

     T-lowerExt-2    UCZAA  WhiteFlow-4   AAWhiteSt-4   ...  SteamFlow-4   \
1           329.067  1.549       537.201         6.076  ...        60.012
2           329.260  1.600       549.611         0.000  ...        61.304
3           331.142  1.604       623.362         6.054  ...        68.496
5           325.195  1.436       628.245         6.020  ...        65.225
6           326.982  1.434       696.766         0.000  ...        72.989
..              ...    ...           ...           ...  ...           ...
276         322.485  1.590       568.752         6.170  ...        67.678
296         313.147  1.546       496.460         6.340  ...        60.119
297         315.558  1.515       491.374         0.000  ...        60.424
298         311.041  1.635       532.419         6.340  ...        65.561
307         332.485  1.522       631.514         0.000  ...        71.286

     Lower-HeatT-3  Upper-HeatT-3   ChipMass-4   WeakLiquorF   BlackFlow-2   \
1          330.823         304.879      163.202       665.975      1297.317
2          329.140         303.383      164.013       677.534      1327.072
3          328.875         302.254      181.487       767.853      1324.461
5          322.103         298.517      165.814       826.243       907.641
6          322.982         296.080      182.018       784.281       929.527
..             ...             ...          ...           ...           ...
276        331.854         309.346      160.061       910.013      1381.389
296        332.615         308.575      141.076       997.904      1334.703
297        331.980         308.078      140.301       975.016      1344.835
298        332.924         307.626      145.299       832.906      1344.708
307        328.699         300.706      180.229       903.605      1323.082

     WeakWashF   SteamHeatF-3   T-Top-Chips-4   SulphidityL-4
1       241.182         46.603         251.406           29.11
2       237.272         51.795         251.335            0.00
3       239.478         54.846         250.312           29.02
5       595.875         52.807         249.580           30.34
6       201.272         58.118         248.741            0.00
..          ...            ...             ...             ...
276     441.934         51.466         252.216           29.59
296     389.497         46.206         252.423           30.43
297     388.676         47.803         252.311            0.00
298     388.911         49.524         251.833           30.29
307     232.729         54.503         250.084            0.00

[226 rows x 22 columns]

In [ ]:
DataSet1.describe()

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
count,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,...,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000,226.000000
mean,20.690487,14.673491,85.882181,1255.288916,264.664912,356.861681,325.341124,1.487146,603.242482,3.098164,...,67.545478,324.752212,299.655420,164.220102,874.123035,1149.895257,273.739403,49.810239,251.177779,15.391987
std,2.982916,1.297369,7.033155,47.896055,74.345135,7.466897,5.557537,0.108054,61.052197,3.078138,...,4.914301,4.526481,4.383788,11.423269,120.259977,150.321416,163.452307,4.143153,1.221296,15.297984
min,12.480000,10.833000,68.645000,1084.083000,61.783000,340.222000,310.421000,1.182000,468.841000,0.000000,...,52.962000,318.051000,293.312000,133.878000,596.446000,838.948000,0.000000,38.283000,248.359000,0.000000
25%,18.457500,13.850000,80.984000,1221.926000,220.356000,350.704250,322.355500,1.429000,549.611000,0.000000,...,63.954000,321.179500,296.338500,156.091000,784.366750,1014.977000,149.331750,46.639750,250.290750,0.000000
50%,20.775000,14.729000,84.967000,1280.291500,270.965000,357.560500,326.508500,1.492000,602.508000,5.904500,...,68.147000,322.380000,297.636500,164.333000,866.170000,1126.513500,283.079500,50.128500,251.233000,29.065000
75%,23.010000,15.708000,91.178750,1289.254000,322.492000,361.555000,329.264500,1.556000,653.358500,6.140000,...,71.760750,329.575000,303.777000,172.555000,968.683250,1302.847000,414.599750,52.889250,252.240000,30.437500
max,27.600000,16.958000,108.104000,1351.240000,419.014000,375.047000,337.012000,1.712000,731.394000,6.340000,...,75.974000,333.223000,309.854000,189.268000,1132.181000,1392.868000,715.715000,59.564000,254.122000,32.840000